export default shoes = [
  {
    id: 1,
    name: "Nike Air Force 1 '07",
    height: "Low",
    gender: "Unisex",
    sizes: [40, 41, 43, 45],
    colors: ["white"],
    price: 100,
  },
  {
    id: 2,
    name: "Nike Court Vision Mid Next Nature",
    height: "Mid",
    gender: "Unisex",
    sizes: [38, 41, 42, 45],
    colors: ["white", "black"],
    price: 95,
  },
  {
    id: 3,
    name: "Nike Blazer Mid '77 Vintage",
    height: "Mid",
    gender: "Unisex",
    sizes: [38.5, 38, 41, 43.5],
    colors: ["white", "black"],
    price: 110,
  },
  {
    id: 4,
    name: "Nike Blazer Mid '77 Vintage",
    height: "Mid",
    gender: "Unisex",
    sizes: [38.5, 38, 41, 43.5],
    colors: ["white", "black"],
    price: 150,
  },
  {
    id: 5,
    name: "Air Jordan 1 Zoom CMFT 2",
    height: "High",
    gender: "Unisex",
    sizes: [38.5, 38, 40, 40.5, 44],
    colors: ["white", "gray"],
    price: 140,
  },
  {
    id: 6,
    name: "Air Jordan 1 Zoom CMFT 2",
    height: "High",
    gender: "Women",
    sizes: [38, 40, 41],
    colors: ["white", "yellow", "multi"],
    price: 80,
  },
  {
    id: 7,
    name: "Nike V2K Run",
    height: "Low",
    gender: "Women",
    sizes: [38.5, 38, 40],
    colors: ["white", "yellow", "purple"],
    price: 95,
  },
  {
    id: 8,
    name: "Air Jordan 1 Low G",
    height: "Low",
    gender: "Women",
    sizes: [38.5, 39, 43],
    colors: ["white", "purple"],
    price: 156,
  },
  {
    id: 9,
    name: "Air Jordan 1 Low SE",
    height: "Low",
    gender: "Men",
    sizes: [38.5, 40, 43, 44, 45],
    colors: ["white", "black", "multi"],
    price: 136,
  },
  {
    id: 10,
    name: "Nike Air Force 1 High By You",
    height: "High",
    gender: "Men",
    sizes: [40, 43, 44, 45],
    colors: ["multi"],
    price: 200,
  },
];
