import { imgsShoes } from "./imgs";
function randomDate(start, end, startHour, endHour) {
  var date = new Date(+start + Math.random() * (end - start));
  var hour = (startHour + Math.random() * (endHour - startHour)) | 0;
  date.setHours(hour);
  return date;
}
export const shoes = [
  {
    id: 1,
    img: imgsShoes.AirForce1.main,
    addImgs: imgsShoes.AirForce1.addImgs,
    name: "Nike Air Force 1 '07",
    height: "Low",
    gender: "Unisex",
    sizes: [40, 41, 43, 45],
    colors: ["white"],
    price: 100.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 2,
    img: imgsShoes.CourtVision.main,
    addImgs: imgsShoes.CourtVision.addImgs,
    name: "Nike Court Vision Mid Next Nature",
    height: "Mid",
    gender: "Unisex",
    sizes: [38, 41, 42, 45],
    colors: ["white", "black"],
    price: 40.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 3,
    img: imgsShoes.Blazer.main,
    addImgs: imgsShoes.Blazer.addImgs,
    name: "Nike Blazer Mid '77 Vintage",
    height: "Mid",
    gender: "Unisex",
    sizes: [38.5, 38, 41, 43.5],
    colors: ["white", "black"],
    price: 110.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 4,
    img: imgsShoes.Blazer.main,
    addImgs: imgsShoes.Blazer.addImgs,
    name: "Nike Blazer Mid '77 Vintage",
    height: "Mid",
    gender: "Unisex",
    sizes: [38.5, 38, 41, 43.5],
    colors: ["white", "black"],
    price: 150.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 5,
    img: imgsShoes.jordanZoom.main,
    addImgs: imgsShoes.jordanZoom.addImgs,
    name: "Air Jordan 1 Zoom CMFT 2",
    height: "High",
    gender: "Unisex",
    sizes: [38.5, 38, 40, 40.5, 44],
    colors: ["white", "gray"],
    price: 140.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 6,
    img: imgsShoes.jordanZoom2.main,
    addImgs: imgsShoes.jordanZoom2.addImgs,
    name: "Air Jordan 1 Zoom CMFT 2",
    height: "High",
    gender: "Women",
    sizes: [38, 40, 41],
    colors: ["white", "yellow", "multi"],
    price: 80.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 7,
    img: imgsShoes.v2k.main,
    addImgs: imgsShoes.v2k.addImgs,
    name: "Nike V2K Run",
    height: "Low",
    gender: "Women",
    sizes: [38.5, 38, 40],
    colors: ["white", "yellow", "purple"],
    price: 95.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 8,
    img: imgsShoes.jordanLowG.main,
    addImgs: imgsShoes.jordanLowG.addImgs,
    name: "Air Jordan 1 Low G",
    height: "Low",
    gender: "Women",
    sizes: [38.5, 39, 43],
    colors: ["white", "purple"],
    price: 156.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 9,
    img: imgsShoes.jordanLowSE.main,
    addImgs: imgsShoes.jordanLowSE.addImgs,
    name: "Air Jordan 1 Low SE",
    height: "Low",
    gender: "Men",
    sizes: [38.5, 40, 43, 44, 45],
    colors: ["white", "black", "multi"],
    price: 136.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
  {
    id: 10,
    img: imgsShoes.AirForseByYou.main,
    addImgs: imgsShoes.AirForseByYou.addImgs,
    name: "Nike Air Force 1 High By You",
    height: "High",
    gender: "Men",
    sizes: [40, 43, 44, 45],
    colors: ["multi"],
    price: 200.99,
    date: randomDate(new Date(2000, 0, 1), new Date(), 0, 24),
  },
];
